apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    co.elastic.logs/module: elasticsearch
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: es01
  name: es01
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: es01
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        co.elastic.logs/module: elasticsearch
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/elastic: "true"
        io.kompose.service: es01
    spec:
      containers:
        - env:
            - name: ELASTIC_PASSWORD
            - name: bootstrap.memory_lock
              value: "true"
            - name: cluster.name
            - name: discovery.type
              value: single-node
            - name: node.name
              value: es01
            - name: xpack.license.self_generated.type
            - name: xpack.security.enabled
              value: "true"
            - name: xpack.security.http.ssl.certificate
              value: certs/es01/es01.crt
            - name: xpack.security.http.ssl.certificate_authorities
              value: certs/ca/ca.crt
            - name: xpack.security.http.ssl.enabled
              value: "true"
            - name: xpack.security.http.ssl.key
              value: certs/es01/es01.key
            - name: xpack.security.transport.ssl.certificate
              value: certs/es01/es01.crt
            - name: xpack.security.transport.ssl.certificate_authorities
              value: certs/ca/ca.crt
            - name: xpack.security.transport.ssl.enabled
              value: "true"
            - name: xpack.security.transport.ssl.key
              value: certs/es01/es01.key
            - name: xpack.security.transport.ssl.verification_mode
              value: certificate
          image: 'docker.elastic.co/elasticsearch/elasticsearch:'
          livenessProbe:
            exec:
              command:
                - curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'
            failureThreshold: 120
            periodSeconds: 10
            timeoutSeconds: 10
          name: es01
          ports:
            - containerPort: 9200
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/config/certs
              name: certs
            - mountPath: /usr/share/elasticsearch/data
              name: esdata01
      restartPolicy: Always
      volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: certs
        - name: esdata01
          persistentVolumeClaim:
            claimName: esdata01
