apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    co.elastic.logs/module: kibana
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kibana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        co.elastic.logs/module: kibana
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/elastic: "true"
        io.kompose.service: kibana
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              value: https://es01:9200
            - name: ELASTICSEARCH_PASSWORD
            - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
              value: config/certs/ca/ca.crt
            - name: ELASTICSEARCH_USERNAME
              value: kibana_system
            - name: SERVERNAME
              value: kibana
            - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
            - name: XPACK_REPORTING_ENCRYPTIONKEY
            - name: XPACK_SECURITY_ENCRYPTIONKEY
          image: 'docker.elastic.co/kibana/kibana:'
          livenessProbe:
            exec:
              command:
                - curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'
            failureThreshold: 120
            periodSeconds: 10
            timeoutSeconds: 10
          name: kibana
          ports:
            - containerPort: 5601
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/kibana/config/certs
              name: certs
            - mountPath: /usr/share/kibana/data
              name: kibanadata
      restartPolicy: Always
      volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: certs
        - name: kibanadata
          persistentVolumeClaim:
            claimName: kibanadata
