apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: "mangement"
      port: 15672
      targetPort: 15672
    - name: "server"
      port: 5672
      targetPort: 5672
  selector:
    rq_service: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      rq_service: rabbitmq
  template:
    metadata:
      labels:
        rq_service: rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              value: password123
            - name: RABBITMQ_DEFAULT_USER
              value: admin
            - name: RABBITMQ_DEFAULT_VHOST
              value: my_vhost
          image: rabbitmq:3-management
          name: rabbitmq
          ports:
            - containerPort: 15672
            - containerPort: 5672
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
      hostname: my-rabbit
      restartPolicy: Always
