---
apiVersion: v1
kind: Service
metadata:
  name: adminapi-service
  labels:
    app: adminapi
spec:
  ports:
  - port: 3000
    protocol: TCP
    name: http
  selector:
    app: adminapi
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminapi-deployment
  labels:
    app: adminapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminapi
  template:
    metadata:
      labels:
        app: adminapi
    spec: # Pod spec
      containers:
      - name: adminapi
        image: rasmuskibshede/adminapi:latest
        ports:
        - containerPort: 3000