---
apiVersion: v1
kind: Service
metadata:
  name: cinemaapi-service
  labels:
    app: cinemaapi
spec:
  ports:
    - port: 3002
      protocol: TCP
      name: http
  selector:
    app: cinemaapi
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinemaapi-deployment
  labels:
    app: cinemaapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinemaapi
  template:
    metadata:
      labels:
        app: cinemaapi
    spec: # Pod spec
      containers:
        - name: cinemaapi
          image: rasmuskibshede/cinemaapi:latest
          ports:
            - containerPort: 3002
          env:
            - name: ELASTIC_HOST
              value: http://esservice
            - name: ELASTIC_USERNAME
              value: elastic
            - name: ELASTIC_PASSWORD
              value: password123
            - name: RMQ_QUEUE
              value: Elastic_QUEUE
            - name: RABBITMQ_VHOST
              value: my_vhost
            - name: RMQ_URL
              value: amqp://admin:password123@rabbitmq-service/my_vhost
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
