---
apiVersion: v1
kind: Service
metadata:
  name: indexapi-service
  labels:
    app: indexapi
spec:
  ports:
    - port: 3001
  selector:
    app: indexapi
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexapi-deployment
  labels:
    app: indexapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexapi
  template:
    metadata:
      labels:
        app: indexapi
    spec: # Pod spec
      containers:
        - name: indexapi
          image: rasmuskibshede/indexelasticsearch:latest
          ports:
            - containerPort: 3001
          env:
            - name: ELASTIC_HOST
              value: http://elasticsearch-service:9200
            - name: ELASTIC_USERNAME
              value: elastic
            - name: ELASTIC_PASSWORD
              value: password123
            - name: RMQ_QUEUE
              value: index_api.screening
            - name: RMQ_URL
              value: amqp://admin:password123@rabbitmq-service/my_vhost
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
