apiVersion: v1
kind: Service
metadata:
  name: transactionapi-service
  labels:
    app: transactionapi
spec:
  ports:
    - port: 3003
  selector:
    app: transactionapi
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactionapi-deployment
  labels:
    app: transactionapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactionapi
  template:
    metadata:
      labels:
        app: transactionapi
    spec: # Pod spec
      containers:
        - name: mycontainer
          image: rasmuskibshede/transactionapi:latest
          ports:
            - containerPort: 3003
          env:
            - name: RMQ_URL
              value: "amqp://admin:password123@rabbitmq-service/my_vhost"
            - name: TRANSACTION_QUEUE
              value: transaction_api.order
            - name: ADMIN_QUEUE
              value: admin_api.order_received
            - name: EMAIL_QUEUE
              value: email_api.declined
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
