apiVersion: v1
kind: Service
metadata:
  name: esservice
spec:
  selector: 
    app: elasticsearch
  type: NodePort  
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 31200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1 
  template: 
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:8.13.0
        resources:
          requests:
            memory: 4Gi
          limits:
            memory: 5Gi
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: discovery.type
          value: single-node