apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: mywebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywebapp
  template:
    metadata:
      labels:
        app: mywebapp
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: dockerhubusername/mywebapp
        ports:
        - containerPort: 80