apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: certs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: es-service
spec:
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: es
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es
  template:
    metadata:
      labels:
        app: es
    spec:
      containers:
        - name: es
          image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
          ports:
            - containerPort: 9200
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/config/certs
              name: certs
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
      volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: certs
        - name: es-data
          persistentVolumeClaim:
            claimName: es-data
