apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibanadata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
    - port: 5601
      targetPort: 5601
  selector:
    app: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.13.0
          ports:
            - containerPort: 5601
          volumeMounts:
            - mountPath: /usr/share/kibana/config/certs
              name: certs
            - mountPath: /usr/share/kibana/data
              name: kibanadata
      volumes:
        - name: certs
          persistentVolumeClaim:
            claimName: certs
        - name: kibanadata
          persistentVolumeClaim:
            claimName: kibanadata
